---
- name: Install SSM Agent x86_64
  dnf:
    name: 'https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm'
    state: present
    disable_gpg_check: true
  when: ansible_architecture == "x86_64"
  become: true
  tags:
    - aws

- name: Install SSM Agent aarch
  dnf:
    name: 'https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_arm64/amazon-ssm-agent.rpm'
    state: present
    disable_gpg_check: true
  when: ansible_architecture == "aarch64"
  become: true
  tags:
    - aws

- name: Enable SSM Agent
  service:
    name: amazon-ssm-agent
    enabled: true
    state: started
  become: true
  tags:
    - aws
