---
- name: Install AWSCLI Prereqs
  package:
    name:
      - unzip
    state: latest
  become: true
  tags:
    - aws_cli

- name: Download AWSCLI Installer x86_64
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: true
  when: ansible_architecture == "x86_64"
  tags:
    - aws_cli

- name: Download AWSCLI Installer aarch
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip
    dest: /tmp
    remote_src: true
  when: ansible_architecture == "aarch64"
  tags:
    - aws_cli

- name: Install AWSCLI
  command: /tmp/aws/install
  args:
    creates: /usr/local/aws-cli
  become: true
  tags:
    - aws_cli
