---
- name: Add repository
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - docker

- name: Install Docker
  package:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
  tags:
    - docker

- name: Enable Docker at Startup.
  service:
    name: docker
    enabled: true
    state: started
  become: true
  tags:
    - docker
